### ISSUE TITLE
How reliable is the code now?

### ISSUE THREAD

**Issue by keon** [gpujs/gpu.js#129]
"Made under 24 hours for a NUS Hackers hackathon, out of 68 competing projects."
I haven't checked out the internals but the quote above from the website makes me wonder how reliable the code is because... you know how codes are written in hackathons.

![](http://redsunsoft.com/site_content/uploads/2014/06/hackathon-code1.png)

**Comment by abhisheksoni27** [comment]
@keon So, how about you **actually** check the internals, and then throw calumnies?

**Comment by keon** [comment]
I will, but are you going to require that to every users?
Having a test coverage rate badge or something would help.

**Comment by fuzzie360** [comment]
@keon, I understand the need for a test coverage rate badge, but to test the project currently you need a GPU which is not very cheap to rent out on the internet. Maybe we can add a pre-commit hook to automatically run a the test suite and generate a badge, but I wouldn't put it at a priority at the moment.

I'd suggest more demos on the homepage instead.

**Comment by keon** [comment]
I see. I was considering to build a simple neural net lib on top of this. I'll decide after checking it out.

**Comment by robertleeplummerjr** [comment]
Two suggestions here: We could simply have a link to open unit tests so they run on the user's browser and second we should look for hosts that give gpu time to open source projects.  @keon, ty for your insight here!

**Comment by robertleeplummerjr** [comment]
Booya: https://www.quora.com/Are-there-any-free-cloud-services-for-open-source-and-academic-research-projects

**Comment by fuzzie360** [comment]
If we're going to go the browser hosted unit tests route, we're probably going to need two sets, one for general features, and another for intensive, in depth tests. I'm afraid it might take too to run the entire gauntlet, and lockups and freezes probably won't leave a good impression anyway.

**Comment by robertleeplummerjr** [comment]
@keon Currently I'm working on the https://github.com/harthur-org/brain.js to do something similar.  We are ironing out some of the more advanced features.  Link will be posted shortly.

**Comment by robertleeplummerjr** [comment]
@fuzzie360 I say just expose the unit tests to the world.  They don't take long to run, and they look great.  If something does popup from them not working right, we fix it.  As we get more and more test coverage we can reevaluate to diverge if needed.

**Comment by fuzzie360** [comment]
Okay then, we shall put the link together with the stable v1.0 release on the homepage and a link in the Github README for the `develop` branch.

If only we could somehow crowdsource the benchmarks. That would be the perfect cost saving solution IMO. The issue is we cannot authenticate the local benchmark runs of our users. But the hardware spread available would be amazing. I guess we can put a submit github issue button that automatically collects the hardware data for us on the page when we put it up.

**Comment by abhisheksoni27** [comment]
**FeedForward Neural Network** using `gpu.js` https://gist.github.com/abhisheksoni27/051cc6c9ef74de7dbd58c683816d41f8

**Comment by robertleeplummerjr** [comment]
Note about @abhisheksoni27's link, we are still working to resolve a few issues on it

**Comment by PicoCreator** [comment]
@fuzzie360 : If it helps, i can just leave a computer on in the office with a crap GPU to automate the test for master branch i suppose?

But since its gonna be a crap GPU, its not for benchmarking for checking if it works.

@keon : We have already a few interesting use cases in academia, however that being said. If its for anything serious in production (and not building a hack ontop of this hack haha). I would recommend waiting for v1. Alternatively for Neural Net, get in touch with @robertleeplummerjr, he is working on integrating this with brain.js

**Comment by keon** [comment]
@robertleeplummerjr interesting... I might be able to help. It would be much better to contribute to something that exists. For now I am going to catch up with the code written so far in brain.js :)

**Comment by robertleeplummerjr** [comment]
Today @abhisheksoni27 got neural net running forward and back, but for some reason error rate isn't dropping.  Serious performance improvements to come with it actually learning!

**Comment by robertleeplummerjr** [comment]
I believe we cracked the neural net error dropping problem, we'll probably see sometime tomorrow, but in short it was array flattening for #132 (doh!).

**Comment by abhisheksoni27** [comment]
@robertleeplummerjr AWESOME! Great work, Sir. The error is going down. :tada: 

![](http://i.imgur.com/M1nEp7h.gif)

**Comment by robertleeplummerjr** [comment]
😍

**Comment by robertleeplummerjr** [comment]
So, to answer the original, we are well tested.

**Comment by keon** [comment]
@robertleeplummerjr cool!
