### ISSUE TITLE
Support for large floating point values beyond int range

### ISSUE THREAD

**Issue by abhisheksoni27** [gpujs/gpu.js#132]
I am only iterating through with one input, only once.

It works fine up to `calculateDeltas`, then weights go to `-Infinity`.

Here's the kernel used to `changeWeights`:

```js
    function buildChangeWeights(){
        function addR(c, w, x, y) {
           return c[y][x] + w[y][x];
        }
        
        for (let layer = 1; layer <= outputLayer; layer++) {
            const kernel = gpu.createKernelMap([addR], function(changes, weights){
                return addR(changes, weights, this.thread.x, this.thread.y);        
            }).setDimensions([sizes[layer-1], sizes[layer]]);
            
            weightsPropagate[layer] = kernel;
            
        }    
    }
```

Here's a unit test for this issue: #133

**Comment by PicoCreator** [comment]
We may actually need to consider a major rewrite on the GPU shader transmission code. If we are to properly support large float numbers including Infinity.

Currently what happens in conversion : is we take the "JS Number" -> "An integer" with a fixed multiplier -> "WebGL float"

As a result numbers out of bound, including infinity, from that integer. Would fail sadly =(

An alternative would be "JS Number" -> "custom binary float" -> "WebGL float"

**Comment by PicoCreator** [comment]
Hmmm, normally my weights in ML is 0 ~ 1 : So need to consider if we need this in v1 (or later)

**Comment by robertleeplummerjr** [comment]
Turns out, it was an issue with flatten.  I took the liberty to rewrite how we were flattening.  We were cloning into an array, which we then sent to a typed array (ie, cloning, and then cloning again), and I figured: why not just read to the typed array and cut out the middleman.  In short: that is what I did, and now we are even faster, more performant, and use less resources than prior on both cpu and gpu.
