### ISSUE TITLE
Will it be possible to declare arrays?

### ISSUE THREAD

**Issue by wagenaartje** [gpujs/gpu.js#161]
I need to have some temporary data in my parallised function. However, I am unable to do any of the following:

```js
const myFunc = gpu.createKernel(function () {
  return this.thread.x;
}, {
  dimensions: [20],
  constants: { test: [] }
});
```

or 

```js
const myFunc = gpu.createKernel(function () {
  var test = [];
  return this.thread.x;
}, {
  dimensions: [20]
});
```

Will this be possible someday?

**Comment by robertleeplummerjr** [comment]
What do you want to do with `constants.test`?

**Comment by ubernaut** [comment]
@robertleeplummerjr 
Thanks for your awesome work and excellent library! 

I was wondering the same thing. I suspect that I can do what I want with createKernelMap/megakernel arrays but I can't quite wrap my brain around it. 

here's a codepen with my issue:

[https://codepen.io/cschroeder/pen/LjKWvP?editors=0010]( https://codepen.io/cschroeder/pen/LjKWvP?editors=0010)

I am writing an n body gravity simulation and I have a version working with GPU.js but it's quite redundant and slower than it could be.  shameless plug: [http://thedagda.co:9000/](http://thedagda.co:9000/)

an Nbody sim is an N^2 simulation where at each step every body (or planet) acceleration is calculated by combining the force of gravity across all other bodies.  

Due to my limited understanding of GPU.js,  the working version, "initGPU()" makes three calls to GPUcomputeAcceleration. One for each dimension and one thread for each body.  Inside, it goes through a loop over every other body where the resultant force acting on the thread's body is summed and temporary variables are computed. 

Because it's broken into three calls, one for each dimension the temporary variables must be recomputed every time and the ultimate result is three huge arrays which must be transposed in javascript. 
(nonetheless it's still about twice as fast as my pure javascript implementation.)

here's a codepen with three versions of a kernel init:
[https://codepen.io/cschroeder/pen/LjKWvP?editors=0010]( https://codepen.io/cschroeder/pen/LjKWvP?editors=0010)
debug mode:
[https://s.codepen.io/cschroeder/debug/LjKWvP/yPkJjGyqdKXk](https://s.codepen.io/cschroeder/debug/LjKWvP/yPkJjGyqdKXk) 

The init function I believe would be the fastest if I could get it to work is:
initGPUArrayMega(){}

that kernel is composed of two functions, An inner function called AccelerateSingle which would open N^2 threads and return a 3D array of acceleration vectors.  and wrapper function which would then sum the forces for each body and return a 2D array of the resultant force on each body. 

The thing is, I can't figure out how to do it without defining an array. which is returned inside of AccelerateSingle. 

Any insight into how I could make it work will earn you my eternal gratitude and a 12 pack of the beer/wine of your choice. 

Here's the working version:

` .
  function initGPU(){
    var gpu = new GPU()
    GPUcomputeAcceleration =  gpu.createKernel(function ( pos,mass, acc,rad,CurrentDimension){
      var G = 2.93558 * Math.pow(10, -4);
      var accx = 0;
      var accy = 0;
      var accz = 0;
      var result = 0;
      for(var i =0; i<this.constants.size; i++){
        var d_x = pos[this.thread.x][0] - pos[i][0];
        var d_y = pos[this.thread.x][1] - pos[i][1];
        var d_z = pos[this.thread.x][2] - pos[i][2];
        var radius = Math.pow(d_x, 2) + Math.pow(d_y, 2) + Math.pow(d_z, 2);
        var rad2 = Math.sqrt(radius);
        var grav_mag = 0.0;
        if (this.thread.x!=0 && this.thread.x != i && rad2 > 0.333 * (rad[i] + rad[this.thread.x])) {
          grav_mag = G / (Math.pow((radius ), (3.0 / 2.0)));
          if(CurrentDimension ==0){
            var grav_x = grav_mag * d_x;
            accx=accx+ (0-(acc[this.thread.x][0] + grav_x * mass[i]));
          }else if(CurrentDimension ==1){
            var grav_y = grav_mag * d_y;
            accy=accy+ (0-(acc[this.thread.x][1] + grav_y * mass[i]));
          }else{
            var grav_z = grav_mag * d_z;
            accz=accx+( 0-(acc[this.thread.x][2] + grav_z * mass[i]));
          }
        } else {                            
          //collision detected
        }
      }
    if(CurrentDimension ==0){
      return accx;
    }else if(CurrentDimension ==1){
      return accy;
    }else{
      return accz;
    }
  },{dimensions:[this.gridSystem.pos.length],
     constants: {size:this.gridSystem.pos.length},
    loopMaxIterations:this.gridSystem.pos.length});
  }
    `

**Comment by robertleeplummerjr** [comment]
You are speaking my language. Let me take a look in the morning.

**Comment by robertleeplummerjr** [comment]
My initial thought is that you are iterating using the same code, three times, and using an `if`.  Why not just use two dimensions?

Removing the if generally speeds things up substantially.

**Comment by robertleeplummerjr** [comment]
@wagenaartje can you give us a bit more definition as to what you are trying to accomplish?

**Comment by robertleeplummerjr** [comment]
This doesn't seem possible with existing technologies.  That may change down the road, will go ahead and close due to limitations GPU's and to keep backlog clean.
