### ISSUE TITLE
Bitwise Operators in Kernel Function?

### ISSUE THREAD

**Issue by t-mullen** [gpujs/gpu.js#166]
Is it possible to use bitwise operators within the kernel function?

If not, will replacing these with normal arithmetic still be faster than without GPU.js?

**Comment by fuzzie360** [comment]
@RationalCoding there are presently no bitwise operations supported in WebGL1. WebGL2 will support the operators but it does mean we have to polyfill using regular arithmetic in WebGL1 which have not been implemented yet.

What you can do for now is use https://github.com/gpujs/gpu.js/commit/d5cb8bbd37c19395d6ab2a51ad96d86ad2964761 to implement your own polyfill version (all platforms), or use WebGL2 offered in Firefox (but it won't work in other browsers yet).

As for performance, there will be additional overhead due to the extra instructions, but I am confident if your work size is large enough, it would still be faster than on CPU. Hopefully, its not too large a size such that its unusable.

**Comment by RationalCoding** [comment]
What is the difference between the `addGLSLFunction` and the ordinary `addFunction`?

**Comment by RationalCoding** [comment]
Thanks, I'll go the polyfill route.

**Comment by RationalCoding** [comment]
It seems Chrome implemented WebGL 2 last year: https://caniuse.com/#feat=webgl2

gpu.js is throwing an error because the bitshift operators only accept integers as their right-hand operands. Seems this is waiting on integer support then.

**Comment by robertleeplummerjr** [comment]
The idea with gpu.js is to have fallback support.  I already started writing webgl 2.0.  you'll see much of it is already commented out, as I was kind of testing it out.  I believe we will target webgl 2.0 after V1 release.

**Comment by robertleeplummerjr** [comment]
I believe this is now resolved.  Can we get a test perhaps?

**Comment by mccoysc** [comment]
now i have got an error if i do some bit operations like x^y……any solutions?

**Comment by zhuker** [comment]
+1

**Comment by robertleeplummerjr** [comment]
Fixed in https://github.com/gpujs/gpu.js/commit/2c4ef75e510897a412b62385cbff952bd046c644
