### ISSUE TITLE
Incorrect Results from Kernel

### ISSUE THREAD

**Issue by RationalCoding** [gpujs/gpu.js#167]
Some inputs for simple kernel functions can return incorrect results.

The simplest example is multiplication by 2:

```javascript
var timesTwo = gpu.createKernel(function (num) { 
  return num * 2
}).setDimensions([1])

timesTwo(821892087)[0] // 1643784192

821892087*2 // 1643784174
```

It's off by 18. A small difference, but still enough to break SHA. Is there any way to enforce accuracy, or is this a tradeoff we are stuck with?

**Comment by fuzzie360** [comment]
Hi @RationalCoding, the reason you are seeing this is because the numbers inside the kernel are all Float32 which is the maximum allowable by WebGL. You can verify with the following JS code:

```
Math.fround(821892087*2) // 1643784192
```

I'm sorry but you will need to do one of the following: 

1) Do clever tricks like spiting the number representation into 2 Float32 numbers.
2) Wait for integer mode support (help is always welcome!)

**Comment by fuzzie360** [comment]
Hmm, it is possible to use https://github.com/gpujs/gpu.js/commit/d5cb8bbd37c19395d6ab2a51ad96d86ad2964761 if you need to deal with overflows for a limited part of the algorithm.

**Comment by RationalCoding** [comment]
Ok, so it's Float32 accuracy. That's something I can handle. Thanks.

Is the relevant part of that commit the `addGLSLFunction` method?

**Comment by RationalCoding** [comment]
I see, I'll need to write it in GLSL. Thanks.
