### ISSUE TITLE
NodeJS GPU "Emulator"

### ISSUE THREAD

**Issue by TheLarkInn** [gpujs/gpu.js#249]
Since node doesn't have OpenCL support, I wonder if I could request a feature that would emulate running GPU bound code in Node by spinning up a headless chrome instance and executing in Chrome via it's remote chrome protocol apis. 

This way hopefully when support (if ever) lands, one could pop out the "emulator" for the real deal.

**Comment by robertleeplummerjr** [comment]
For testing, you could do this: https://github.com/gpujs/gpu-mock.js

This will allow you to debug the kernel function but within the javascript stack.  In the mean time, the GPU will simply fallback to CPU.  The other option could be to do something like: https://electronjs.org/

**Comment by TheLarkInn** [comment]
What about consuming capabilities used here for NodeJS. I don't actually want to do any graphical programming besides leveraging the ability to hardware accelerate some complex things we are doing in webpack (graph algos cache serialization/deserialization, threading). I'll be researching this a bit more.

**Comment by robertleeplummerjr** [comment]
I really think the answer here is to use the above listed gpu-mock library.  This forces compilation of a very simple kernel with loops inside so that easy debugging can take place.  This way you can stick `debugger`'s inside the kernel, and actually debug as if you were on the gpu.  Going to go ahead and close for the time being.
