### ISSUE TITLE
Nested variable declarations in for loop difference (of CPU vs GPU)

### ISSUE THREAD

**Issue by picoCreator** [gpujs/gpu.js#31]
Kudos for @staceytay for doing up a ray tracer demo

http://staceytay.com/raytracer/

Sadly for the GPU.JS team, it also shows that we may have a canvas related bug for rendering mode (floating point accuracy?). Specifically for "Lambertian reflectance"

Maybe its his code, or our code (most probably ours), but yea =(

@TODO : investigate and fix

To replicate, switch between CPU and GPU with Lambertian reflectance "on" and pay close attentions to the shadow shading

**Comment by staceytay** [comment]
Thanks for checking out the demo! And also for pointing out the bug. The change in lighting is actually a bug in my code, it was looping for lights using `i` and somewhere below I redeclared the `i`. Fixed it in my latest [commit](https://github.com/staceytay/raytracer/commit/5a933f27bc47614c5c6d444fe5c375051f24320d). Think it works when in GPU mode probably because the generated code takes into account the scope for `i`?

**Comment by picoCreator** [comment]
@staceytay : ideally, both CPU and GPU mode should be consistent. And if it isn't it should throw a warning / exception.

For clarification, is the following what you meant?

```
for(var i=0; i<max; ++i) {
    //do something
}
for(var i=0; i<max; ++i) {
    //do something
}

```

And somehow the 2nd i gets "buggy"??

Because if redeclaration of vars is buggy, I should throw a warning / exception on that.

**Comment by staceytay** [comment]
Yup that's what I meant for the `for` loop.

That's true, the two modes should be consistent. On a related note, there's also an issue with using `this.constants` in kernel functions in CPU mode. In CPU mode you'll get a `this.constants is undefined` error although it works in GPU mode.

**Comment by fuzzie360** [comment]
@picoCreator You've got it upside down. JavaScript does not have block scoping, it has functional scoping. Its GLSL that has block scoping. We must follow JavaScript semantics so ideally `i` should be same scope instead of different scope on the gpu (crazy, I know).

I suppose we could either implement variable hoisting, or treat this as undefined behaviour. Personally don't see any sane use for variable hoisting and I wish I could rather just emit a big error about undefined behaviour if hoisting is used anywhere in the kernel. I don't mind if anybody wants to implement it though.

**Comment by sawman** [comment]
Hey Stace! Good to see you here haha. Sorry for hijacking the issue, just wanted to say hi :). Sadly I'm the languages guy. Haven't touched the code in ages, but I will after exams so yeaaa. We were talking about using a precompiler for CPU mode to enforce block scope right? Implementing scope either way is easy for GPU mode, it's just another layer in the environment. Personally I think keeping it JS and cui is better, as long as people are smart about their scoping.

**Comment by staceytay** [comment]
Hi Matthew! Yea I think keeping it JS, and emitting a warning or putting this somewhere in the documentation is fine. It's more about the user expecting the code to be the same in both CPU and GPU mode.

**Comment by sawman** [comment]
Merged with #35

**Comment by picoCreator** [comment]
@fuzzie360 : yup your right had it backwards, lol. Realised it when i did up the issue 31 test case.

@sawman : My current suggestion would be to actually flag out a warning, as we generate the code from AST. On repeated variable declaration (repeated var declares are a bad idea anyway)

This would be an extension of the addFunction script, which already keeps track of function declarations and calling trace (automatically skipping functions that do not get called).

**Comment by robertleeplummerjr** [comment]
Handled here: https://github.com/robertleeplummerjr/gpu.js/commit/b999dc611d1531ac8df3d893b40ba3e16e723f0e#diff-d02bb56a83c0737e60796c843f0857c9R461
From: https://github.com/gpujs/gpu.js/pull/66
