### ISSUE TITLE
int support

### ISSUE THREAD

**Issue by sawman** [gpujs/gpu.js#36]
We want to investigate how to implement int type. This would mean emitting different code depending on which mode we run the compiler in.

**Comment by robertleeplummerjr** [comment]
Done!

**Comment by fuzzie360** [comment]
@robertleeplummerjr we don't actually support integers. @sawman was working on type inference support to increase our type support from float to int, float and vec.

It's need because, for example, the number 2,147,483,647 will be converted to floating point 2,147,483,650 resulting in reduced integer dynamic range.

So, I'm going to leave this open for now :)

**Comment by robertleeplummerjr** [comment]
Nice

**Comment by RationalCoding** [comment]
I'm interested in taking a look at this, since it's needed for a large number of applications.

What kind of type inference? AFAIK, there's no way to differentiate `1.0` and `1` in Javascript. We wouldn't want floats with no decimal part being interpreted as integers.

Would a `setInputType` API similar to `setOutput` make sense? ie)

```javascript
gpu.createKernel(function(a, b) {
   // ...
}).setInputType('float32', 'int32');
```

Another alternative is to expose a method of casting numbers back and forth. Like `var myInt = Math.castToInt(myFloat)` would become `highp int myInt = int(myFloat);`. Although this would be easy to implement, it shifts typing to runtime, which is not great.

**Comment by RationalCoding** [comment]
There is also an unused `paramTypes` option in the kernel that seems to be related to this issue.

**Comment by robertleeplummerjr** [comment]
There are a couple ways we could handle this.  First off, we could differentiate `1.0` vs `1` in the function itself, because it is parsed as a string to glsl.  That part would be easy.  Also, because inheritance is already traced via function and child function recursively (I think only one level at this point, but could easily be n nested) that part is easy as well.  So really the need comes from the use case mentioned (I am open to other ideas, as it is late and I am fairly tired from launching rockets and trying to find them with my kids), which I think is fairly fantastically simple.  This would give us a non-duck type detection, woohoo!  The only down side I see is that it separates the inputs from their type, which isn't a huge deal, but it'd be nice to get them closer together.  In any case, I cannot think of a better means that isn't as straightforward, and would very much so welcome the added `setInputType` or, I think more appropriate `setInputTypes` method if it were gifted or a future target.

**Comment by RationalCoding** [comment]
Yes, the string approach would work fine for literals within the function. I see integer literals are being explicitly converted to floats right now in the same way.

Although I think `setTypes` is best, we could use some kind of naming format to set types within the function itself.
```javascript
gpu.createKernel(function (a, int_b, float_c) {
   // a is float (default)
   // int_b is int (or rename it to just "b"?)
   // float_c is float
})
```

I haven't considered what might be required for vec support. Should we map them to some sort of `gpu.Vec` object, since Javascript has no tuples?

**Comment by robertleeplummerjr** [comment]
I'm honestly trying to find fault with this, but I really don't mind it.  This even gives us the option to do variable declaration internally that is typed.  Another thing to address would be the kernel output type.  Perhaps we could:

```js
gpu.createIntKernel(...
gpu.createFloatKernel(...
gpu.createBoolKernel(...
```

Just some thoughts.

**Comment by RationalCoding** [comment]
That would only allow same-typed parameters. Why not overload the createKernel to accept an optional type array:

```javascript
gpu.createKernel(['float32', 'int32'], function(a, b) {
   // a is a float32
   // b is an int32
});
```

No strange notation, and it keeps the types and parameters "syntactically close".

**Comment by RationalCoding** [comment]
Oh I misread, you mean regarding output... perhaps both?

```javascript
gpu.createInt32Kernel(['float32', 'int32'], function(a, b) {
   // a is a float32
   // b is an int32
   // returns int32
});
```

**Comment by robertleeplummerjr** [comment]
I dislike that that added array breaks up the continuity of the type here.  But I'm willing to see the light on it, I generally resort to the saying: "but can I explain it to my 6 year old?", and if I cannot, then I don't.

**Comment by RationalCoding** [comment]
If you want them closer, we could hack together type annotation using the ES6 default parameter syntax:

```javascript
gpu.createInt32Kernel(function(a='float32', b='int32') {
   // a is a float32
   // b is an int32
   // returns int32
});
```

I really don't like my previous idea of using special variable names to specify type ie) `int32_a` as variable names would either have to repeat the prefix, or they would change within the function.

**Comment by robertleeplummerjr** [comment]
This is now partially implemented in that when you use constants, it writes in the int's when it builds the kernel.  Just fyi.

**Comment by robertleeplummerjr** [comment]
Now fully supported in v2 rc 13.  Either by directly declaring via `argumentTypes: ['Integer']` or using a new option `strictIntegers: true` which will turn argument types that are detected to be integers, to integers (will become v2 rc14): https://github.com/gpujs/gpu.js/tree/rc-14-cleanup#gpucreatekernel-settings

**Comment by devill** [comment]
Does that make it possible to force integer output? It's not clear for me how this is supposed to be used in code.
