### ISSUE TITLE
unexpected div_with_int_check error

### ISSUE THREAD

**Issue by Jonathan-D-Ip** [gpujs/gpu.js#413]
https://jsfiddle.net/yg9o3fq2/10/

**Comment by Jonathan-D-Ip** [comment]
I am using Chrome Version 71.0.3578.98 (Official Build) (64-bit) on a late-2015 MacBook Air.

**Comment by Jonathan-D-Ip** [comment]
[https://i.imgur.com/7Y0eDoa.png](url)

**Comment by kamil-kielczewski** [comment]
Did you try to optimize that code?

**Comment by Jonathan-D-Ip** [comment]
in what way? i didn’t change the gpu.js content

**Comment by Jonathan-D-Ip** [comment]
Hello? Any updates? Or any suggestions? Any feedback would be helpful.

**Comment by robertleeplummerjr** [comment]
I believe the issue is that of referencing `uTexSize` (`uTexSize.x` & `uTexSize.y`) directly, which is not a documented feature.  By referencing this value, two things happen:

* We are not able to resolve the value, as it is not a user input (function variable, argument) and so we're leaving it up to the compiler to throw an error if it doesn't exist
* The variable does exist, but its type is not correct.

The way around this is to use values that are exposed as official features, if possible.  The most applicable seems to be `this.output.x` or `this.output.y`, which are both floats, and should be what you are looking for.  If those values are not, I'll have to take a deeper dive here.

**Comment by Jonathan-D-Ip** [comment]
thanks

**Comment by robertleeplummerjr** [comment]
I believe this was resolved.
