### ISSUE TITLE
Error: 2.0.0-rc3 does not render anything

### ISSUE THREAD

**Issue by atolkachiov** [gpujs/gpu.js#443]
Simple sandbox is here: 
https://codesandbox.io/s/zlk91p690m

It works perfectly when I pass `mode: "cpu"` option, but try to comment it out and it does not render anything on the canvas. I tried to play with parameters but still no luck. 

Everything works with the latest stable `1.10.*` but I would like to explore all the new v2 features, and on-canvas rendering is essential part of my ML project.

**Comment by robertleeplummerjr** [comment]
Hi @atolkachiov!

Ty for such a beautiful and simple demo.  I believe this issue was resolved in https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.4

I liked your demo so much [I added it to the examples](https://github.com/gpujs/gpu.js/blob/master/examples/slow-fade.html)!

Let me know if that doesn't resolve the issue.
