### ISSUE TITLE
performance: gpu takes 6 - 10 times longer

### ISSUE THREAD

**Issue by lorankary** [gpujs/gpu.js#466]
My operation is to take the square root of the sum of squares.

What I am finding is that it takes me 1 - 2 seconds to perform without the gpu and 13 seconds with the gpu.  

Is there some explanation?  Please see attached.

[performance.html.zip](https://github.com/gpujs/gpu.js/files/3157956/performance.html.zip)

MacBook Pro mid 2015 2.5 ghz i7
AMD Radeon R9 M370X 2048 MB
Intel Iris Pro 1536 MB

**Comment by HarshKhandeparkar** [comment]
How many operations do you want to do. Like how many distances to find?

**Comment by lorankary** [comment]
Just for the purpose of performance testing I am finding 10000 distances and I am repeating it 10000 times.  I think that's 100 million calculations.  In the actual student game project, it could be more than 10000 distances to calculate 60 times per second.

**Comment by HarshKhandeparkar** [comment]
Maybe that is the reason. 10000 calculations is like nothing for the CPU. GPU becomes beneficial when there are like 10 million calculations to do.

**Comment by lorankary** [comment]
I think I am doing 100 million (10K * 10K) distance calculations for performance evaluation purposes.

**Comment by HarshKhandeparkar** [comment]
Do you want to calculate distances from 100M points or 10K points?

**Comment by HarshKhandeparkar** [comment]
Do you want to calculate distances from 100M points or 10K points?

**Comment by HarshKhandeparkar** [comment]
What is the output size of the kernel you are using?

**Comment by lorankary** [comment]
I attached my test code in the first panel and you should be able to grab that and see everything I am doing and see what results you get.  Thanks for all your help.

**Comment by HarshKhandeparkar** [comment]
I was asking questions since I cannot see the code on my phone. I am not at
home right now. I will check it in a few hours and let you know. Thanks and
sorry

**Comment by robertleeplummerjr** [comment]
His entire source code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GPU.js Collision Detection Performance</title>
</head>
<body>
<script src="../gpu.js/bin/gpu-browser.js"></script>
<script>

    var coords = [];
    var output = [];
    for(let i = 0; i < 10000; i++){
        coords.push([Math.random()*800, Math.random()*600]);
    }
    let loc = {x: Math.random()*800, y: Math.random()*600};

    let start = Date.now();
    for(let j = 0; j < 10000; j++){
        output = [];
        for(let i = 0; i < coords.length; i++){
            let dist = Math.sqrt(Math.pow(loc.x-coords[i][0], 2) + Math.pow(loc.y-coords[i][1], 2));
            output.push(dist);
        }
    }
    let stop = Date.now();
    console.log(stop-start + " ms");
    // Use the gpu to calculate the distance between one
    // coordinate pair and each coordinate pair in an Array
    // https://github.com/gpujs/gpu.js/issues/464

    const gpu = new GPU();
    const kernelFunc = function(coords,loc_x, loc_y){

    const x = coords[this.thread.x][0];
    const y = coords[this.thread.x][1];

    return Math.sqrt(Math.pow((loc_x - x), 2) + Math.pow((loc_y - y), 2))
    }


    const collisions = gpu.createKernel(kernelFunc);

    //coords = [[0, 2], [2, 3], [5, 8]];

    collisions.setOutput([10000]);  // dimension of 1D array
    start = Date.now();
    for(let j = 0; j < 10000; j++){
        output = collisions(coords,loc.x,loc.y);
    }
    stop = Date.now();
    console.log(stop-start + " ms");

</script>
</body>
</html>

```

**Comment by robertleeplummerjr** [comment]
Your output for GPU is, in-fact, 10000 (output size) * 10000 (repeatedly setting `output`).  To answer why this is slower is because first the math is very easy for the GPU, and so you aren't really using the GPU for its strengths.  Give it a harder problem to crack.  And second, you are going directly to an array from the GPU, and not using pipeline.

The reason you'd want to use GPU for a problem is because:
1. It is a hard mathematical problem.
2. There are many steps (more than one?) to the problem.
3. Much of your implementation already uses the GPU, and so if you have a simple step in processing, and yet the math around said simple step already is using pipeline.
4. You have A LOT of operations to do.

To see the benefit of GPU, lets start by:
1. Setup the `Math.random()` calls that build the initial array, on the GPU, and use pipeline.
2. Putting ALL of the operations, all 10000 * 10000, in a single array
3. Building the kernel first, before measuring computation using `kernel.build(arg1, arg2, arg3...)` (just like when you call `kernel(arg1, arg2, arg3...)`.
4. Measure computation after the kernel it built, to get an accurate idea of how it can break down your problem.
5. Presumably, you are going to do something with these measurements?  Move that to the GPU as well, and build similarly to the above, then switch pipeline between these kernels, on. 
6. Measure all of it.

I'm not guaranteeing you'll see a massive improvement in performance, but that should give you a head start.  I tried starting the code you have, but setting up the `Math.random()` calls from the CPU, and I couldn't even get the code to finish in a browser.  I'd be excited to see what happens when all the math is on the GPU.  Going to close for the time being as I believe we have sufficiently answered the original question, but are now experimenting on how to get it faster.

**Comment by HarshKhandeparkar** [comment]
10000 is a very small output size. Calculating this is a piece of cake for a CPU. If your output size was like 100 million which it isn't, the GPU would have been faster that the CPU.

**Comment by lorankary** [comment]
Thanks for all the helpful suggestions and let me respond to a couple of things.  One thing is that all the Math.random() setup is not part of the computing I need to do -- it's just to have something to test that is equivalent to my actual task.  The second is that my actual task is only on the order of 10K distance computations, not 100M.  So the bottom line is that my actual task is not on the order of magnitude that would make it faster to use the gpu.  But I learned something and enjoyed the exercise.
