### ISSUE TITLE
What is the meaning of the setting precision?

### ISSUE THREAD

**Issue by Steve73** [gpujs/gpu.js#479]
What is the meaning of the kernel setting 'precision'?

The documentation says 

> 'single' or 'unsigned' - if 'single' output texture uses float32 for each colour channel rather than 8

what does 8 mean. float8?

looking at one of your test examples:

```
  const original = new Float32Array([1, 2, 3, 4, 5, 6, 7, 8, 9]);
  const gpu = new GPU({ mode });
  const kernel = gpu.createKernel(function(packed) {
    return packed[this.thread.x];
  }, {
    output: [9],
    precision: 'unsigned'
  });

  const result = kernel(original);
```

what does precision: 'unsigned' do? When I change the precision to 'single' nothing changes. The result in both cases is:

`Float32Array(9) [1, 2, 3, 4, 5, 6, 7, 8, 9]`

Thanks for any clarifications!

**Comment by robertleeplummerjr** [comment]
>What is the meaning of the kernel setting 'precision'?

It has to do with using `gl.FLOAT` (precision = 'single') or `gl.UNSIGNED_BYTE` (precision = 'unsigned').

For each it implies:
* precision = 'unsigned': A 32 bit float is bit shifted into 4 parts, each being of 8 bits, and each one of those parts.
  * This can require much more effort to store each value, as has to be sliced up (packed) into a each Red, Green, Blue, and Alpha channel and assembled (unpacked), even between kernels, even when using textures.
  * This isn't always the slower approach, it depends on your graphics card.
  * This implies each channel is 8 bits, and that (at time of writing) they are each a part of a 32 bit value.
  * Some precision is lost from the packing and unpacking, hence "unsigned".
* precision = 'single': A 32 bit float is read _directly back_ ,to the CPU or stored in a texture, in either an Red, Green, Blue, or Alpha channel.
  * This implies each channel is 32 bit.
  * This can be read _directly back_ to a `Float32Array`.
  * This implies there is no loss of precision, within the confines of 'single' precision.

>what does precision: 'unsigned' do? When I change the precision to 'single' nothing changes.

![](http://www.reactiongifs.com/r/exc.gif)

This is exactly what we'd hope for on the outside, but internally, I can assure you, _many_ things change.  This is to help with:

* Testing
* Configurability.
* Backwards compatibility, some cards do not allow for single precision float 32
* An unwavering responsibility to pack as many straightforward features into GPU.js without sacrificing performance.
* Relentless testing, in Chrome, Firefox, Safari, Edge, Node, in Windows, OSX, and Linix.  With plans of testing in Android and iOS.


Why would we provide this capability? (I hear you potentially ask)
* Because it is faster in a lot of cases to directly use singed floats, rather than unpacking and packing (or packing and unpacking ;)).
* It lead to us being able to use arrays (Array(2), Array(3), and Array(4)) as a return result from a kernel.
   * Now we're potentially planning on adding simpler arrays with smaller bits [as you are aware](https://github.com/gpujs/gpu.js/issues/441#issuecomment-497135167).
* We don't want to lock you into using just what GPU.js approves, we want GPU.js to be a doorway to easily pry open and peer into, with meager javascript, the heart of the Tardis that is the GPU.

For fun, try doing this:
```js
const kernelWithSinglePrecision = gpu.createKernel(function..., {
  precision: 'single'
});
const kernelWithUnsignedPrecision = gpu.createKernel(function..., {
  precision: 'single'
});
const singlePrecisionString = kernelWithSinglePrecision.toString(arg1, arg2, arg3);
const unsignedPrecisionString = kernelWithUnsignedPrecision.toString(arg1, arg2, arg3);
```

Then compare the `singlePrecisionString` and `unsignedPrecisionString` outputs.

Let me know if you need any further detail.
