### ISSUE TITLE
Any suggestions for node.js + nooocl usage?

### ISSUE THREAD

**Issue by vird** [gpujs/gpu.js#52]
Nodejs can use this https://github.com/unbornchikken/NOOOCL at serverside. I really like transpiler idea, but I want serverside runtime. Is it possible? Is there any example? Async API?
Note. Yes I understand, that openCL != webGL.

**Comment by fuzzie360** [comment]
Hi vird, I like this idea very much. By going to OpenCL we can do some really serious computing done. We will start moving in this direction after an overhaul of our compiler.

**Comment by robertleeplummerjr** [comment]
I don't think this is a "nice to have" but rather "a must".  I'll see what I can do.

**Comment by robertleeplummerjr** [comment]
I've asked @unbornchikken if he has interest in helping, but I fully plan on assisting with this initiative after v1 is released.

**Comment by unbornchikken** [comment]
Hi, I have interest of course but unfortunately ain't got much time for opensource nowadays (two little children). If you have any concrete issue that I could help you out, lemme now.

**Comment by robertleeplummerjr** [comment]
ty for the mention, and the brief time you spent replying.  I mentioned your name because I know your passion.  In the mean time ty for building NOOOCL, great things will come from it!
![](https://media4.giphy.com/media/LtUTh1MsPyGWI/giphy.gif)

**Comment by hujiulong** [comment]
any news?

**Comment by robertleeplummerjr** [comment]
I started on this a couple days ago, tinkering.  I can say opencl
integration is WAY simpler than webgl.

**Comment by jsphweid** [comment]
Looking forward to this. By the way... version 0.0.0...?? Not even 0.0.1?

**Comment by frenchfaso** [comment]
Me too!
Are there any news about gpu support on nodejs?
btw, gpujs is the best lib ever :1st_place_medal:

**Comment by robertleeplummerjr** [comment]
I've got a proof of concept working for nooocl, @unbornchikken, is there any way you could bump version support for opencl 2?

**Comment by robertleeplummerjr** [comment]
@frenchfaso, ty very much!  But...

![](https://media.giphy.com/media/xT0xeodrsrEa7k0Br2/giphy.gif)

**Comment by nsantini** [comment]
@robertleeplummerjr any way I can help on your efforts?

**Comment by robertleeplummerjr** [comment]
The initial work has been done here: https://github.com/gpujs/gpu.js/tree/area-52

Ideally we'd start with simple unit tests, building up simple features.

It is still a high priority, I've just been super busy using the already exposed API in brain.js.org.  When opencl is landed, js will have an enterprise gpu accelerated platform.  Preemptive huzzah!

**Comment by robertleeplummerjr** [comment]
https://github.com/mikeseven/node-opencl/issues/55#issuecomment-366839756

It installs now...

**Comment by robertleeplummerjr** [comment]
@nsantini Want to help still?

**Comment by Steve73** [comment]
Any news, when gpu is supported serverside? Thank you for maintaining this great project!

**Comment by robertleeplummerjr** [comment]
I'm finishing up a few things for a release of brain.js hopefully at the end if the month.  After that this issue will be my complete obsession.

**Comment by phawxby** [comment]
Looking forward to these changes coming in. I'd like to try integrating int [pixelmatch](https://github.com/mapbox/pixelmatch), I imagine the performance boost will be enormous. Great project!

**Comment by arjunmehta** [comment]
Hi there, also a huge fan. Is there any chance of node.js support in the near future? Any help needed?

**Comment by robertleeplummerjr** [comment]
@arjunmehta help would be greatly appreciated.  If anyone is interesting in assisting I jump on slack via bri.im, and lets talk.

**Comment by arjunmehta** [comment]
@robertleeplummerjr I had a cursory look at the code and seems like you're using webGL instead of webCL/openCL. Have you looked into using https://github.com/mikeseven/node-webgl or https://github.com/stackgl/headless-gl ?

Seems like these are projects that would plug in very easily into this one

**Comment by robertleeplummerjr** [comment]
Opencl is the first planned target.

**Comment by robertleeplummerjr** [comment]
I don't see any if the above targets being difficult to use as a target from the existing work.   Just coordinating efforts to concur the world.

**Comment by arjunmehta** [comment]
I have a proof of concept up using `headless-gl`

https://github.com/gpujs/gpu.js/pull/404

**Comment by robertleeplummerjr** [comment]
Progressing on this today fellas.  I've got all unit tests running on it, and modified things so the headless-gl module is installed just in time, but running into an issue (I think) with google Angle missing up the shader.  Will know more shortly.

**Comment by robertleeplummerjr** [comment]
So I got it "working", but it appears that ANGLE misinterprets less than comparisons with floats, and because of the recent advances with https://github.com/google/node-gles/pull/3, I think I might wait till that is ready.

**Comment by robertleeplummerjr** [comment]
Ty for the suggestions, I'll be sure to try it if my current path doesn't succeeded, or perhaps even add as another driver, just in case.  As a positive point, I reached out to @nkreeger who manages https://github.com/google/node-gles/pull/3 and he seems to be fairly helpful to advance work together.  I was able to get the project to build, and though I'm not yet working with textures that output numbers, I was able to get the environment mostly working, with the exception of a few missing wrapper functions (adding uniforms, and sub frame buffers), so I'll be adding those in the coming days, and see where it goes.

**Comment by robertleeplummerjr** [comment]
Hoping right along: https://github.com/google/node-gles/pull/4/files

**Comment by robertleeplummerjr** [comment]
Was thinking this through and I believe my current plan of attack is this: There is still a lot of missing functionality from `node-gles` having compiled it, and seeing output etc. and although I believe that it is the future, we are _extremely_ close with `headless-gl`, minus a few small bugs.

Because of how much `headless-gl`:
* has been noticed (and I assume used, [even though it isn't thoroughly listed on npmjs.org](https://www.npmjs.com/package/headless-gl))
* that it already is 98% of the way working
* that it is a drop in install

I'd like to go ahead and resolve the issues that exist with it **first**.  This will give us low hanging fruit, and a path for upgrade, rather than just waiting and hoping for `node-gles` to land at v1.

Note: We are _sooooo cloooose!_!

![](https://media3.giphy.com/media/Qaxd5XpgDWMso/giphy.gif)

The flexibility with `headless-gl` will also give us something to meet with `node-gles`, and I'm not shy (as you guys know) have already having contributed there.

Verbose current plan of attack:
* Resolve fragment parsing issue with float's using existing source, which I believe is our one _big_ hangup.  This is super important, because all methods generally work, I get stable output, etc.  Also we have a ton of unit tests in gpu.js where we can gauge how close we are to full support.
* Open up PR that adds new functionality in `headless-gl`.
 * Because the library isn't maintained, I'll likely reach out to see if that job can be passed on to me for the time being.
 * If this for some reason isn't accepted, I'll just open my own fork, and continue reluctantly there.  Good grief, how many times can we fork this thing as actual projects?  Lets combine efforts guys!
* Resolve a few other small bugs adding primitive unit tests for each directly in the project where they can be tracked and administered.
* Possibly upgrade to latest `ANGLE` and ensure tests pass.
  * If tests bork badly, leave in maintenance mode.
* Wait and continue to help with `node-gles` until it reaches a point it exceeds the usefulness of `headless-gl` (ie, we get unit tests passing and possibly webgl2, which isn't currently being developed towards)
* Migrate to `node-gles`

In either case, mark my words, this _will_ be working shortly.

![](https://media2.giphy.com/media/xRFiDPIVR2Dfy/giphy.gif)

**Comment by robertleeplummerjr** [comment]
@arjunmehta if I go ahead and push up my changes, maybe we can work together, simultaneously providing a back end for https://github.com/GoogleChrome/puppeteer?

**Comment by robertleeplummerjr** [comment]
Stepped into the parser found that the glsl is being rewritten internally, which I expected.  Small steps.

**Comment by robertleeplummerjr** [comment]
I've captured the error, glsl source before it is translated, after it is translated, and reproduction javascript test here: https://gist.github.com/robertleeplummerjr/aa0a8bb9250426e5a3e9e360482b3083

I'm now passed google angle, and into dependencies.  Getting closer.

**Comment by robertleeplummerjr** [comment]
Rather than keeping noise going here, I'm going to start tracking the bug here: https://github.com/stackgl/headless-gl/issues/140

Bigger updates will come here.

**Comment by robertleeplummerjr** [comment]
Current update: https://github.com/gpujs/gpu.js/issues/216#issuecomment-466994822

Node.js GPU support is imminent.  Stay tuned for the coming days, this will likely lead to a release.

**Comment by wbrickner** [comment]
Is this now supported in v2?  Been following for a few years now :P 
Wondering what the status is, can't seem to figure out if it's landed.

**Comment by robertleeplummerjr** [comment]
Node is now supported, there is a bug in windows with multiple render targets that will be addressed likely after the release of v2.  A few small bugs related to typings and direct float handling are being resolved now.  Nearly there.  v2 will be a force to be reckoned with for stability.

**Comment by wbrickner** [comment]
That's amazing to hear! You've delivered a beautiful thing!

**Comment by robertleeplummerjr** [comment]
I believe since this uses HeadlessGL, and release is imminent, this issue is now resolved.  Ty guys for all your hard work and cheering.

**Comment by arjunmehta** [comment]
@robertleeplummerjr 🎉
Fantastic!!
