### ISSUE TITLE
Are these matrix operations supported?

### ISSUE THREAD

**Issue by TheInvoker** [gpujs/gpu.js#57]
Hi, does your library support doing these matrix operations? Note all the dimensions will be known on runtime.

![capture1](https://cloud.githubusercontent.com/assets/5560751/23228507/c3647b0c-f90a-11e6-8cde-c76e2f33de51.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5560751/23228508/c369afa0-f90a-11e6-8ae1-4afe214f5f3b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5560751/23228506/c3637f18-f90a-11e6-8edb-284375b83074.PNG)

**Comment by fuzzie360** [comment]
The matrix multiplication example on the front page of http://gpu.rocks/ can be modified to run with dynamic dimension size, or external constants. Within the webgl constraints we have these pros and cons of each method:

# Dynamic size
Pros:
- Needs only single compilation

Cons:
- Loop max iteration must be set to a proper value, will not work if the length in one dimension exceed loop max iterations
- Slowdown on matrices considerably smaller than loop max iteration value

# External Constants
Pros:
- Will work fast on all inputs

Cons:
- Needs to compile at least once for every matrix size input


Matrix addition and vector multiplication can be written too but because the complexity is much much lower than matrix multiplication, the runtime and webgl pipeline overhead might cause gpu.js to run the program slower than in pure javascript. Vector multiplication might still be fast enough depending on the input size.
