### ISSUE TITLE
source not a function string (Arrow functions not supported?)

### ISSUE THREAD

**Issue by creepinson** [gpujs/gpu.js#593]
## *What* is wrong?

gpu-browser.min.js:14 Uncaught Error: source not a function string

GPU.js does not work with es6 functions and requires me to put "function()" instead of "() =>"

## *Where* does it happen?

```js
const train = gpu.createKernel((data) => {
  network.train(data, {
    iterations: 5000,
    log: (stats) => {
      console.log(stats)
    },
  })
}).setOutput([100]);

train(trainingData)
```

## *How* do we replicate the issue?

Use arrow functions in createKernel

## *How* important is this (1-5)?

1.5

## Expected behavior (i.e. solution)

It should have worked or given another error if it didn't, but  it shouldn't have required me to use "function() {"...

**Comment by HarshKhandeparkar** [comment]
Things like `network.train` and `console.log` will not work anyway. Can you provide a simpler kernel that reproduces the same error?

**Comment by robertleeplummerjr** [comment]
The context from within a GPU.js kernel's function is separate from where the `gpu.createKernel()` function is called from.  The lack of support for arrow function for the _kernel function_ is by design, as to obtain coordinates, you need `this` which is the scope from within the kernel, and not that from where it was created.

The other reason is that the functions need referenced names.

It seems like you want to use brain.js's `NeuralNetworkGPU`, which uses GPU.js.
