### ISSUE TITLE
Is it possible to improve number precision?

### ISSUE THREAD

**Issue by GirkovArpa** [gpujs/gpu.js#597]
![Canine Tech Support](https://i.imgur.com/uLkspma.jpg)

## *What* is wrong?
A math function is less precise on the GPU than on the CPU.

## *Where* does it happen?
In GPU.js when trying to run a math function in node.js on my Windows 10 64 bit laptop.

## *How* do we replicate the issue?
    'use strict';
    const { GPU } = require('gpu.js');
    const gpu = new GPU();
    
    const concatNumbersCPU = (a, b) => a * Math.pow(10, Math.floor(Math.log(b) / Math.log(10)) + 1) + b;
    
    const concatNumbersGPU = gpu.createKernel(function (a, b) {
      return a * Math.pow(10, Math.floor(Math.log(b) / Math.log(10)) + 1) + b;
    }, { output: [1] });
    
    console.log(concatNumbersCPU(12345, 67890));    // => 1234567890
    console.log(concatNumbersGPU(12345, 67890)[0]); // => 1234567552

## *How* important is this (1-5)?
1

## Expected behavior (i.e. solution)
I expected both functions to return 1234567890.

## Other Comments
I'm trying to encode strings as numbers; e.g., `1 == A` ,`12 == AB`, etc.

**Comment by robertleeplummerjr** [comment]
It would seem to be possible if GPU.js had an integer texture feature: https://observablehq.com/@robertleeplummerjr/gpu-js-issue-597

Wanna contribute?

**Comment by GirkovArpa** [comment]
Currently I believe I can return strings of length 12 encoded as arrays of length 4 where each array entry is a 6-digit integer, encoding 3 letters.

Would be cool if I can figure out how to improve that, I will take a look.  But I know nothing of shader language 🤷‍♂

**Comment by HarshKhandeparkar** [comment]
Hi @GirkovArpa the backend uses 32bit floats. Floats store numbers in a fundamentally different way. They store the numbers in binary scientific notation i.e. `M * 2^E`. 

Where M is approximately a 24bit integer in binary. 

The exponent E is what does the main trick. E can be positive or even negative. Negative values lead to fractions (but in base 2). [Read More](http://stackoverflow.com/questions/4806944/ddg#4806966)

This is what creates the issue. Some numbers that may be simple in base 10 may not be so simple to write in this format. For example multiples of 5. There is no way you can write multiples of 5 if the number `M` is not a multiple of 5. Since the exponential part is only base 2, if you want multiples of 5, or 3, you need to change the numeric part i.e. `M`.

Now since M is small, numbers which are large multiples of 5 or 3 like 5^11 for e.g. cannot be written in float form because 5^11 exceeds the range of 24bit `M`. Although you could make numbers much bigger than 5^11 by tweaking the exponent `E`, there is no way you can get 5^11 specifically. (The computer only approximates this value)

Hence this causes the precision issue and there isn't a bery good fix for it. Except one way that I can think of. You can divide by a multiple of 5 and then multiply by it (when displaying). If the final output is 5^12, you can divide this output by 5^2 and the GPU will register 5^10 which it can store accurately. When displaying, display `output * 5^2` on the CPU side.

CPU can use 64bit floats which give a much larger range of values. So, the CPU will be able to display these values
