### ISSUE TITLE
gpu get canves img  hashcode

### ISSUE THREAD

**Issue by menglinxi** [gpujs/gpu.js#69]
how to get hashcode of canvas by gpu calculation

**Comment by PicoCreator** [comment]
By hashcode do u mean canvas fingerprinting?

https://browserleaks.com/canvas

**Comment by menglinxi** [comment]
yes i know fingerprinting and try it，but i want gpu.js create canvas，and gpu.js get this canvas hashcode,one computer browers the hashcode is same,other cumputer browers the hashcode is not same。use gpu.js create canvas and fingerprinting get this canvas hashcode，All computer browsers are the same value。target use gpu.js one device create one canvas hashcode.  the hashcode can cross browser on computer or mobile phone tracking this device。thanks！

**Comment by PicoCreator** [comment]
Hmm theoretically speaking then if your doing multiple floating point calculations, it could be unique to each individual computer. The plus side, is you do not need to actually handle the canvas.

However it could also fluctuate, because by specification the GPU does not guarantee accuracy beyond a certain margin. Meaning your ending result / hash itself may fluctuate on the same system.

It is worth giving a try.

For canvas specifically, what your asking for is graphical mode. A few not-that-related examples can be found by doing a google search "gpu.js raytracer". 

From then onwards you can build your respective hash function.

**Comment by robertleeplummerjr** [comment]
This is slightly outside the realm of General Purpose of gpgpu, and is more specific purpose, and  because you are dealing directly with the canvas via: `gpu.getCanvas()` which it outside the scope of the purpose of this library.
